# Generated by Django 2.1.4 on 2019-01-12 12:56

import b2b.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.IntegerField()),
                ('date_bid', models.DateTimeField(default=django.utils.timezone.now)),
                ('bid_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(default='default_post_image.jpg', upload_to=b2b.models.get_image_filename, verbose_name='Select an Image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(default=datetime.datetime(2019, 1, 14, 12, 56, 14, 14944, tzinfo=utc), verbose_name='End Date')),
                ('initial_price', models.IntegerField(default=100)),
                ('current_price', models.IntegerField(default=0, verbose_name='Current Bid')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='b2b.Post'),
        ),
        migrations.AddField(
            model_name='bidder',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.Post'),
        ),
    ]
