# Generated by Django 2.1.4 on 2019-01-12 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_auto_20190112_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 12, 56, 51, 639250, tzinfo=utc), verbose_name='End Date'),
        ),
    ]
